/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle_project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Scanner;

public class App {
    

    public static void main(String[] args) throws Exception {
        Scanner s = new Scanner(System.in);
        MemberService mService = MemberService.getInstance();

            System.out.print("아이디 : ");
            String id = s.nextLine();
            if(mService.isDuplicateId(id)){
                System.out.println("이미 가입된 아이디입니다.");
            }else{
                System.out.print("비밀번호 : ");
                String pwd = s.nextLine();
                mService.memberJoin(id, pwd);
                System.out.println("회원가입이 완료되었습니다");
            }


        

    }
}
